#!/usr/bin/env node
/**
 * sync-docs.mjs
 *
 * Reads Docs/docs-split.manifest.json, slices sections from source monoliths
 * in Docs/_source/, rewrites links, prepends an autogen banner, and writes
 * output files to the Docs/ tree.
 *
 * Usage: npm run docs:sync
 *        node tools/docs-sync/sync-docs.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../..');
const DOCS_DIR = join(REPO_ROOT, 'Docs');
const SOURCE_DIR = join(DOCS_DIR, '_source');
const MANIFEST_PATH = join(DOCS_DIR, 'docs-split.manifest.json');

// ─── Helpers ─────────────────────────────────────────────────────────────────

function readSource(filename) {
  const path = join(SOURCE_DIR, filename);
  if (!existsSync(path)) {
    throw new Error(`Source file not found: ${path}`);
  }
  return readFileSync(path, 'utf8');
}

/**
 * Extract the block of text between two heading anchors.
 *
 * start === null → from the beginning of file.
 * end   === null → to the end of file.
 *
 * The match is performed on the raw line, trimmed. If the heading appears
 * more than once the script aborts — anchors must be unique.
 */
function extractSection(text, start, end) {
  const lines = text.split('\n');

  let startIdx = start === null ? 0 : -1;
  let endIdx = end === null ? lines.length : -1;

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trimEnd();

    if (start !== null && startIdx === -1) {
      // exact: true → require the line to equal the anchor exactly (trimmed).
      // default   → require the line to start with the anchor (handles partial
      //             anchors like "## LORE: PROLOGUE" matching the full heading).
      const anchorStart = typeof start === 'object' ? start.text : start;
      const exactStart = typeof start === 'object' && start.exact;
      const matchesStart = exactStart
        ? trimmed === anchorStart.trim()
        : trimmed.startsWith(anchorStart.trim());
      if (matchesStart) startIdx = i;
    }

    if (end !== null && endIdx === -1) {
      const anchorEnd = typeof end === 'object' ? end.text : end;
      const exactEnd = typeof end === 'object' && end.exact;
      const matchesEnd = exactEnd
        ? trimmed === anchorEnd.trim()
        : trimmed.startsWith(anchorEnd.trim());
      if (matchesEnd) endIdx = i;
    }
  }

  const startLabel = start === null ? '(file start)' : (typeof start === 'object' ? start.text : start);
  const endLabel = end === null ? '(file end)' : (typeof end === 'object' ? end.text : end);

  if (start !== null && startIdx === -1) {
    throw new Error(`Start anchor not found: "${startLabel}"`);
  }
  if (end !== null && endIdx === -1) {
    throw new Error(`End anchor not found: "${endLabel}"`);
  }
  if (end !== null && endIdx <= startIdx) {
    throw new Error(`End anchor "${endLabel}" appears before start "${startLabel}" (start=${startIdx}, end=${endIdx})`);
  }

  return lines.slice(startIdx, endIdx).join('\n').trimEnd();
}

/**
 * Apply link rewrites defined in manifest.linkRewrites.
 */
function rewriteLinks(text, rewrites) {
  let result = text;
  for (const { from, to } of rewrites) {
    result = result.split(from).join(to);
  }
  return result;
}

/**
 * Build the autogen banner comment block.
 */
function autogenBanner(source, output) {
  return [
    `<!-- AUTO-GENERATED from _source/${source} -->`,
    `<!-- Output: ${output} -->`,
    `<!-- Do not edit this file directly. Edit _source/${source} and run: npm run docs:sync -->`,
  ].join('\n');
}

/**
 * Build an optional "See also" footer block from manifest seeAlso entries.
 */
function seeAlsoBlock(entries) {
  if (!entries || entries.length === 0) return '';
  const links = entries.map(({ label, path }) => `- [${label}](${path})`).join('\n');
  return `\n\n---\n\n**See also:**\n${links}`;
}

/**
 * Ensure directory exists (recursive).
 */
function ensureDir(filePath) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
const { handMaintained = [], linkRewrites = [], entries } = manifest;

// Cache source file contents so we only read each once.
const sourceCache = {};
function getSource(filename) {
  if (!sourceCache[filename]) {
    sourceCache[filename] = readSource(filename);
  }
  return sourceCache[filename];
}

let written = 0;
let skipped = 0;
const errors = [];

for (const entry of entries) {
  const { source, output, start, end, title, seeAlso } = entry;

  // Skip hand-maintained files.
  if (handMaintained.includes(output)) {
    console.log(`  SKIP  (hand-maintained) ${output}`);
    skipped++;
    continue;
  }

  try {
    const sourceText = getSource(source);
    let content = extractSection(sourceText, start, end);

    // Strip the matched start heading if we also supply a `title` override,
    // so we don't end up with two H1s. Only strip if the extracted section
    // begins with a heading line.
    if (title) {
      const firstLine = content.split('\n')[0].trim();
      if (firstLine.startsWith('#')) {
        content = content.split('\n').slice(1).join('\n').trimStart();
      }
      content = `${title}\n\n${content}`;
    }

    // Apply link rewrites.
    content = rewriteLinks(content, linkRewrites);

    // Append seeAlso footer if defined in the manifest entry.
    content += seeAlsoBlock(seeAlso);

    // Prepend autogen banner.
    const banner = autogenBanner(source, output);
    const finalContent = `${banner}\n\n${content}\n`;

    const outputPath = join(DOCS_DIR, output);
    ensureDir(outputPath);
    writeFileSync(outputPath, finalContent, 'utf8');
    console.log(`  WROTE ${output}`);
    written++;
  } catch (err) {
    errors.push({ output, message: err.message });
    console.error(`  ERROR ${output}: ${err.message}`);
  }
}

console.log(`\nSync complete: ${written} written, ${skipped} skipped, ${errors.length} error(s).`);

if (errors.length > 0) {
  console.error('\nFailed entries:');
  for (const { output, message } of errors) {
    console.error(`  ${output}: ${message}`);
  }
  process.exit(1);
}
